# Generated by Django 5.0.2 on 2024-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondocuments',
            name='admin_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Comments'),
        ),
        migrations.AddField(
            model_name='submissiondocuments',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Status'),
        ),
    ]
