# Generated by Django 5.0.2 on 2024-03-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_is_active_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doc_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
