# Generated by Django 5.0.2 on 2024-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_booking_end_date_remove_booking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='semester_duration',
            field=models.IntegerField(choices=[(1, '1 semester'), (2, '2 semesters')], default=1, verbose_name='Duration in Semesters'),
        ),
    ]
