# Generated by Django 5.0.2 on 2024-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_defaultpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpayment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
